### ISSUE TITLE
Fix DenseVector[Complex].t

### ISSUE THREAD

**Issue by zhuqi259** [scalanlp/breeze#475] opened 2015-12-23 08:05 UTC
```
import breeze.linalg.{DenseMatrix => DM, DenseVector => DV}
import breeze.math.Complex

val m = DM.ones[Int](5, 4)
m(4, ::) := DV(1, 2, 3, 4).t
println(m)

val m1 = DM.ones[Int](5, 4)
m1(4, ::).t := DV(1, 2, 3, 4)
println(m1)

val n = DM.ones[Complex](5, 4)
n(4, ::).t := DV(Complex(1, 1), Complex(2, 2), Complex(3, 3), Complex(4, 4))
println(n)

val n1 = DM.ones[Complex](5, 4)
n1(4, ::) := DV(Complex(1, 1), Complex(2, 2), Complex(3, 3), Complex(4, 4)).t
println(n1)
```

m, m1, n is Compiled well, but not n1. n1 got " could not find implicit value for parameter op: breeze.linalg.operators.OpSet.InPlaceImpl2[breeze.linalg.Transpose[breeze.linalg.DenseVector[breeze.math.Complex]],breeze.linalg.DenseMatrix[breeze.math.Complex]] "

Why m is Right along with n1 is Wrong?
m is showed like the example in https://github.com/scalanlp/breeze/wiki/Quickstart

Maybe it is a simple question. Thanks.

**Comment by dlwh** [comment] 2015-12-23 16:14
Ah, there's some incompleteness in transpose with DenseVector[Complex] because of dealing with hermitian transpose, etc.

What were you expected the transpose to do? take the conjugate, or leave it as is? I assume the latter?

**Comment by zhuqi259** [comment] 2015-12-24 05:37
Many thanks for your explanation.

**Comment by dlwh** [comment] 2015-12-24 05:44
i'm gonna keep it open as a note for me to fix it. But seriously, would you expect .t to take the conjugate or not?

**Comment by zhuqi259** [comment] 2015-12-24 13:21
Oh, I'm sorry for my poor knowledge of some math problems. It might be better if conjugate transpose and simple transpose(maybe it also have an official name) both exist in breeze API like that in matlab.

**Comment by dlwh** [comment] 2017-12-10 21:01
dupe of #233

**Closed by dlwh** 2017-12-10 21:01 UTC
Labels: project
