### ISSUE TITLE
Provide container matrix to avoid excessive allocations

### ISSUE THREAD

**Issue by XapaJIaMnu** [scalanlp/breeze#563] opened 2016-07-15 15:28 UTC
Hey,

In our application we have a lot of `DenseVector * DenseVector.t` operations which produce a matrix (about 20% of our runtime in total).  We suspect that part of the problem is that every time those two vectors are multiplied to produce a matrix, a new `DenseMatrix` object is being created resulting in excessive memory allocations and hence a lot of GC work. Now we actually need to keep only one version of our the matrix so we want to do something like:
`val container = DenseMatrix.zeros[Double](i,j)
container := vector*vector.t
`
Where the container matrix is passed to the function doing the `vector*vector.t`
However we don't see the expected decrease in the runtime or number of objects created in the profiler. I suspect that an intermediate Matrix is still being created. Is that the case?  Could we avoid it?

Cheers,

Nick

**Comment by dlwh** [comment] 2016-07-18 06:58
that's right. Breeze right now is fairly literal and doesn't have the
capacity to do fairly obvious optimizations. It's one of the many things
I'd like to add, but I don't have the bandwidth for it right now. You could
drop down and directly call the blas routines for outer product (dger or
sger) if you wanted.

On Fri, Jul 15, 2016 at 8:28 AM, Nikolay Bogoychev <notifications@github.com

**Comment by dlwh** [comment] 2017-12-10 20:56
dupe of #226

**Closed by dlwh** 2017-12-10 20:56 UTC
Labels: project
