### ISSUE TITLE
StrongWolfeLineSearch

### ISSUE THREAD

**Issue by Chikooo** [scalanlp/breeze#565] opened 2016-07-20 11:06 UTC
I am building neural network using MultilayerPerceptronClassifier.
While training a model I am getting following error. Kindly let me know what is going wrong?

ERROR StrongWolfeLineSearch: Encountered bad values in function evaluation. Decreasing step size to 0.5

**Comment by nikdon** [comment] 2016-07-21 09:03
As mentioned in [sources](https://github.com/scalanlp/breeze/blob/master/math/src/main/scala/breeze/optimize/StrongWolfe.scala#L144-L149), it means that step length **t** is too large and in the next iteration it will be decreased by the factor of 2. Step length **t** used for calculation of **phi**, which is a function we want to minimize.

**Comment by dlwh** [comment] 2017-01-04 00:38
closing since there's no repro and I think it's probably not a bug in the line search.

**Closed by dlwh** 2017-01-04 00:38 UTC
