### ISSUE TITLE
3D Matrix Support

### ISSUE THREAD

**Issue by dschulz72** [scalanlp/breeze#505] opened 2016-03-04 20:42 UTC
Hey there, I'm fairly new to Breeze, so this might be implemented already, but I can't find a way to have a 3+ dimensional matrix. For instance, you might be able to create a new DenseMatrix by calling DenseMatrix(((1, 1, 1), (1, 1, 1), (1, 1, 1)), ((2, 2, 2), (2, 2, 2), (2, 2, 2))). If you could implement this, I'm sure many users would benefit from it.

**Comment by dlwh** [comment] 2016-03-04 21:16
this is probably the single most requested feature in Breeze. I want a
general N-D solution, but don't have the bandwidth

That said, I'd take a PR for DenseTensor3 or whatever.

**Comment by dlwh** [comment] 2017-12-10 20:38
duplicate of #244

**Closed by dlwh** 2017-12-10 20:38 UTC
